name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: make
        
      - name: Run tests
        env:
          MAINNET_RPC_URL: "${{ secrets.MAINNET_RPC_URL }}"
        run: make test